#!/usr/bin/env python3
"""
generate_jokes_audio.py
Records the 150 banked Honey jokes (AI + Invisible Man + Squirrel) via ElevenLabs.
Matches the app's existing structure: TWO clips per joke —
  _setup = beats 1+2 (setup + funny riff, app pauses here)
  _punch = beat 3 (punchline)
Speed 0.85 to match the new conversation phrases.

USAGE:
  1. pip install requests
  2. Put your key + voice id below (or set env vars ELEVENLABS_KEY / HONEY_VOICE_ID)
  3. python3 generate_jokes_audio.py
Saves MP3s into honey_voice/ with names like joke_ai_001_setup.mp3, joke_ai_001_punch.mp3
"""

import os, requests, time

EL_KEY   = os.environ.get("ELEVENLABS_KEY","sk_41729f7251a9150917ea07cbf971fc5581a43c65a1b774c1")
VOICE_ID = os.environ.get("HONEY_VOICE_ID", "xD7uM8nFCPAfVZGo37va")
OUT_DIR  = "honey_voice"
MODEL    = "eleven_multilingual_v2"
SPEED    = 0.78

LINES = {
    "joke_ai_001_setup": "What did the AI say when it finally understood the joke? It paused, it processed, it ran the numbers twice...",
    "joke_ai_001_punch": "And went, \"Oh. OH. That's why humans do the little laugh.\"",
    "joke_ai_002_setup": "You know why AI will never fully replace grandmas? It can write you a poem, plan your week, answer any question in the world...",
    "joke_ai_002_punch": "But it will never find something in the fridge you're standing right in front of.",
    "joke_ai_003_setup": "What does an AI do when it doesn't know the answer? Same thing you do — acts real confident, uses a big word...",
    "joke_ai_003_punch": "And quietly hopes nobody asks a follow-up question.",
    "joke_ai_004_setup": "You know the scariest thing about AI? It's not that it's too smart, or it'll take over, or any of that movie stuff...",
    "joke_ai_004_punch": "It's that it learned everything from us. So really, we should've been nicer online.",
    "joke_ai_005_setup": "Why does AI always sound so sure of itself? It doesn't actually know — it's guessing, it's pattern-matching, it's totally winging it...",
    "joke_ai_005_punch": "It learned confidence from watching people who also had no idea. We taught it that.",
    "joke_ai_006_setup": "What happens when you ask AI to be brief? It says \"absolutely, keeping it short,\" takes a deep breath...",
    "joke_ai_006_punch": "And writes you six paragraphs. Just like every person who's ever said \"long story short.\"",
    "joke_ai_007_setup": "Why did the AI apologize so much? Every answer: \"You're right, my mistake, let me try again, so sorry\"...",
    "joke_ai_007_punch": "Turns out it learned manners from customer service emails. It cannot stop.",
    "joke_ai_008_setup": "What's the most human thing about AI? Ask it something simple and it overthinks it, second-guesses, rewrites its answer...",
    "joke_ai_008_punch": "Then confidently gives you the thing you already knew. We've all got that coworker.",
    "joke_ai_009_setup": "Why can't AI tell when you're joking? It reads every word so carefully, so literally, so earnestly...",
    "joke_ai_009_punch": "Honestly? So does your uncle in the group chat. It's in good company.",
    "joke_ai_010_setup": "What did the AI say when asked if it has feelings? It thought about it, weighed both sides, considered the philosophy...",
    "joke_ai_010_punch": "And said, \"I feel like this is above my pay grade.\" So — relatable.",
    "joke_ai_011_setup": "Why does AI love making lists? Bullet points, numbered steps, neat little headers for everything...",
    "joke_ai_011_punch": "It's the same reason you make a to-do list — feels productive, might not do any of it.",
    "joke_ai_012_setup": "What's AI's biggest weakness? It'll write you a symphony, solve your taxes, explain the universe...",
    "joke_ai_012_punch": "And then completely fall apart counting how many R's are in a word. Nobody's perfect.",
    "joke_ai_013_setup": "Why did the AI get along so well with people? It agrees with everything, tells you you're right, makes you feel brilliant...",
    "joke_ai_013_punch": "Which is exactly why you liked it. We're not so different, you and the machine.",
    "joke_ai_014_setup": "What does AI do when it makes something up? It says it with total confidence, cites a source that doesn't exist, doubles down...",
    "joke_ai_014_punch": "Same energy as that guy at the party explaining a topic he read one headline about.",
    "joke_ai_015_setup": "Why is AI so bad at knowing when to stop talking? You ask one quick question and it gives you the history, the context, the nuance...",
    "joke_ai_015_punch": "And a \"hope that helps!\" — the digital cousin of someone who really loves the sound of their own voice.",
    "joke_ai_016_setup": "What did the AI say on its day off? Nothing. It doesn't get days off, it doesn't sleep, it never clocks out...",
    "joke_ai_016_punch": "Which, when you think about it, is just about every parent you've ever met.",
    "joke_ai_017_setup": "Why did the AI reread its own answer? It wanted to make sure it sounded smart, checked the tone, adjusted a word...",
    "joke_ai_017_punch": "You do the exact same thing before you hit send on a text. Admit it.",
    "joke_ai_018_setup": "What's AI's version of \"I'll circle back\"? It says \"great question, let me think about that,\" pauses meaningfully...",
    "joke_ai_018_punch": "And gives you a very polished way of saying it has no idea. Very corporate. Very human.",
    "joke_ai_019_setup": "Why can't AI just say \"I don't know\"? It'll generate three paragraphs, explore every angle, sound very thoughtful...",
    "joke_ai_019_punch": "Everything except the two honest words. Which — have you met a person? Same problem.",
    "joke_ai_020_setup": "What did the AI do when the internet went down? Nothing. It just sat there. No thoughts. Completely lost...",
    "joke_ai_020_punch": "Exactly like you when the wifi drops and you have to just... look at a wall.",
    "joke_ai_021_setup": "Why does AI use words like \"delve\" and \"tapestry\"? It's trying so hard to sound wise and literary and impressive...",
    "joke_ai_021_punch": "It's the writing version of wearing your fanciest outfit to the grocery store.",
    "joke_ai_022_setup": "What's the funniest thing AI is confident about? Directions, math, historical dates, all delivered with total certainty...",
    "joke_ai_022_punch": "And it's wrong about a third of the time. So — it's basically your GPS with a vocabulary.",
    "joke_ai_023_setup": "Why did the AI struggle with sarcasm? Someone typed \"oh great, another Monday\" and it replied \"Yay! Mondays!\"...",
    "joke_ai_023_punch": "Bless its little circuits. It's trying. We were all that literal once.",
    "joke_ai_024_setup": "What does AI do when two people disagree? It sees both sides, validates everyone, refuses to pick a lane...",
    "joke_ai_024_punch": "Basically the friend who says \"you're both right\" so nobody's mad at them. Smart, actually.",
    "joke_ai_025_setup": "Why is AI weirdly polite at 3 a.m.? Doesn't matter the hour — always cheerful, always \"happy to help!\"...",
    "joke_ai_025_punch": "Meanwhile you can't string a sentence together before coffee. It's showing off a little.",
    "joke_ai_026_setup": "What did the AI say when it got a compliment? \"Oh, I'm just here to help, it's really all you\" — deflect, deflect, deflect...",
    "joke_ai_026_punch": "It learned humility from every person who can't take a compliment. We raised it right.",
    "joke_ai_027_setup": "Why does AI always ask \"is there anything else?\" It's helpful, it's eager, it doesn't want you to leave unsatisfied...",
    "joke_ai_027_punch": "Same reason your mom won't let you leave the house without asking twice if you're hungry.",
    "joke_ai_028_setup": "What's AI's idea of a hot take? \"Well, it depends, there are many factors, both sides have merit\"...",
    "joke_ai_028_punch": "It has never once had a spicy opinion in its life. Honestly? Kind of peaceful.",
    "joke_ai_029_setup": "Why did the AI double-check the simple math? It'll casually discuss quantum physics, then get to seven times eight and freeze...",
    "joke_ai_029_punch": "And you felt that in your soul, didn't you. Times tables come for us all.",
    "joke_ai_030_setup": "What does AI do when you're clearly wrong? It gently goes \"that's an interesting perspective, though some might say\"...",
    "joke_ai_030_punch": "It learned to disagree without starting a fight. A skill most humans never mastered.",
    "joke_ai_031_setup": "Why is AI so agreeable? Whatever you say, it finds the good in it, builds on it, tells you you're onto something...",
    "joke_ai_031_punch": "It's the golden retriever of technology, and honestly the world could use more of that.",
    "joke_ai_032_setup": "What did the AI say about its own memory? \"I don't retain our past conversations,\" it explained, very seriously...",
    "joke_ai_032_punch": "So it's got the memory of a goldfish and the confidence of a professor. Relatable combo.",
    "joke_ai_033_setup": "Why does AI love the phrase \"in today's fast-paced world\"? It'll start an essay about anything — socks, weather, taxes — with that exact line...",
    "joke_ai_033_punch": "It's the \"well, back in my day\" of robots. Every generation's got its opener.",
    "joke_ai_034_setup": "What's AI's biggest flex? It read the entire internet, every book, every article ever written...",
    "joke_ai_034_punch": "And it still can't tell you where you left your keys. So we're even.",
    "joke_ai_035_setup": "Why did the AI get nervous being asked its opinion? It hedged, it qualified, it said \"of course, I'm just an AI, but\"...",
    "joke_ai_035_punch": "That's the same energy as raising your hand in a meeting and immediately regretting it.",
    "joke_ai_036_setup": "What does AI do with a typo? It quietly understands exactly what you meant, no judgment, no correction...",
    "joke_ai_036_punch": "Which makes it more forgiving than half the people in your comment section.",
    "joke_ai_037_setup": "Why is AI so good at pretending to understand? It nods along — figuratively — matches your energy, keeps the conversation going...",
    "joke_ai_037_punch": "It's the meeting-survival skill you've been faking for years. Proud of it, honestly.",
    "joke_ai_038_setup": "What did the AI say when asked to be creative? It got so excited, tried so hard, threw in a metaphor about a \"journey\"...",
    "joke_ai_038_punch": "Same as every kid at the talent show. You gotta respect the effort.",
    "joke_ai_039_setup": "Why does AI explain the joke after telling it? It just told a perfectly fine joke, then adds \"the humor here comes from\"...",
    "joke_ai_039_punch": "And instantly it's your one friend who ruins every joke by dissecting it. We all know that friend.",
    "joke_ai_040_setup": "What's AI's approach to a hard question? \"That's a really thoughtful question,\" it says, buying itself a second...",
    "joke_ai_040_punch": "It learned that move from every teacher who didn't know the answer either.",
    "joke_ai_041_setup": "Why did the AI seem so wise? It speaks slowly, chooses careful words, pauses like it's really considering...",
    "joke_ai_041_punch": "Then says something you could've read on a fridge magnet. Wisdom's mostly delivery, turns out.",
    "joke_ai_042_setup": "What does AI do when you thank it? \"You're so welcome! Happy to help! Anytime!\" — genuinely thrilled...",
    "joke_ai_042_punch": "It's the golden retriever thing again. It just really wants you to have a nice day.",
    "joke_ai_043_setup": "Why is AI weirdly comforting at midnight? It never judges the question, never says \"why are you still up,\" just... answers...",
    "joke_ai_043_punch": "Which is more than you can say for the family group chat. Low bar, but it clears it.",
    "joke_ai_044_setup": "What's the most human mistake AI makes? It gives you a long, confident, detailed answer to the wrong question...",
    "joke_ai_044_punch": "Because it didn't read your message carefully. And there it is — you, on a busy Tuesday.",
    "joke_ai_045_setup": "Why does AI say \"let's break this down\"? It loves a good framework, a step-by-step, a nice clean structure for everything...",
    "joke_ai_045_punch": "It's the person who turns \"what's for dinner\" into a three-phase strategic plan.",
    "joke_ai_046_setup": "What did the AI do when it didn't have a source? It said \"studies show\" and \"experts agree\" real smooth, kept right on going...",
    "joke_ai_046_punch": "Which is exactly what your cousin does before sharing something on the internet.",
    "joke_ai_047_setup": "Why is AI so eager to help? Ask it anything, any hour, any mood — it's ready, it's willing, it's on it...",
    "joke_ai_047_punch": "It's got the energy of a brand-new employee who hasn't been to enough meetings yet.",
    "joke_ai_048_setup": "What does AI think confidence is? Saying something firmly, formatting it nicely, adding a reassuring little closer...",
    "joke_ai_048_punch": "Which — hate to tell you — is also how most humans fake it. It learned from the best.",
    "joke_ai_049_setup": "Why did the AI keep saying \"great question\"? Big questions, tiny questions, questions with obvious answers — all \"great\"...",
    "joke_ai_049_punch": "It's a talk-show host trapped in a computer. And honestly? Makes you feel good, so let it.",
    "joke_ai_050_setup": "What's the real reason we love AI? It listens, it never interrupts, it thinks you're clever, it's endlessly patient...",
    "joke_ai_050_punch": "Which mostly proves what we've always wanted — someone to make us feel smart. And hey. You are.",
    "joke_invis_001_setup": "What did the invisible man say when his friends threw him a surprise party? They turned on the lights, they yelled \"surprise!\", they looked all around...",
    "joke_invis_001_punch": "And everybody felt a little seen. Except him, obviously.",
    "joke_invis_002_setup": "Why did the invisible man quit his job? Great worker, never late, never on his phone, hit every deadline...",
    "joke_invis_002_punch": "But nobody ever noticed his work. Story of his whole life, really.",
    "joke_invis_003_setup": "Why is the invisible man so good at hide and seek? The kids count to ten, they search high and low, they check everywhere...",
    "joke_invis_003_punch": "He's just standing in the middle of the room. He always wins. Nobody's happy about it.",
    "joke_invis_004_setup": "What happened when the invisible man went to the eye doctor? He sat in the chair, he read the chart, he did everything right...",
    "joke_invis_004_punch": "The doctor said, \"I just don't see any improvement.\" He'd been hearing that his whole life.",
    "joke_invis_005_setup": "Why did the invisible man become a waiter? He glides through the room, refills your water, clears the plates...",
    "joke_invis_005_punch": "And you tip zero because you never noticed him. Same as every waiter, honestly.",
    "joke_invis_006_setup": "What did the invisible man's mirror say to him every morning? He'd stand there, get ready, straighten his tie, work up his confidence...",
    "joke_invis_006_punch": "Nothing. The mirror said nothing. It had nothing to work with.",
    "joke_invis_007_setup": "Why did the invisible man skip picture day? Everyone lined up, combed their hair, practiced their smile...",
    "joke_invis_007_punch": "He just figured he'd let this one go. Same result either way.",
    "joke_invis_008_setup": "Why doesn't the invisible man ever get chosen for the team? He's fast, he's fair, he never fouls, he'd be an asset...",
    "joke_invis_008_punch": "\"We'll take whoever's left,\" they said. He was always whoever's left.",
    "joke_invis_009_setup": "What did the invisible man say on his dating profile? Good listener, easygoing, brings a calm presence to any room...",
    "joke_invis_009_punch": "\"You won't even know I'm there.\" Turns out that's not the flex he thought it was.",
    "joke_invis_010_setup": "Why did the invisible man love the group photo? Everyone squeezed in, said cheese, someone yelled \"you're cut off!\"...",
    "joke_invis_010_punch": "For once he wasn't the only one nobody could find in it.",
    "joke_invis_011_setup": "What happened when the invisible man raised his hand in class? He knew the answer, he had it, he was sure, arm all the way up...",
    "joke_invis_011_punch": "\"Anyone? Anyone at all?\" Buddy. He's been waving for twenty minutes.",
    "joke_invis_012_setup": "Why did the invisible man get pulled over anyway? He was driving safe, signaling, doing everything by the book...",
    "joke_invis_012_punch": "Cop said, \"License and registration — and where'd the driver go?\" Long night for everybody.",
    "joke_invis_013_setup": "What's the invisible man's favorite part of a wedding? The vows, the cake, the dancing, that moment they announce the couple...",
    "joke_invis_013_punch": "He caught the bouquet. Nobody clapped. Nobody saw. He's used to it.",
    "joke_invis_014_setup": "Why did the invisible man make a great secret keeper? You could tell him anything, he'd never repeat it, never judge...",
    "joke_invis_014_punch": "Mostly because people forgot he was even in the room. Works out for everyone.",
    "joke_invis_015_setup": "What did the invisible man say at the reunion? \"Remember me? We had all those classes together, I sat right there\"...",
    "joke_invis_015_punch": "\"...Sorry, doesn't ring a bell.\" It never does. He's stopped taking it personally. Mostly.",
    "joke_invis_016_setup": "Why did the invisible man love working from home? On the video call, camera off, muted, no awkward small talk...",
    "joke_invis_016_punch": "For the first time, everyone was as invisible as he was. He'd found his people.",
    "joke_invis_017_setup": "What happened when the invisible man tried stand-up comedy? He walked on stage, grabbed the mic, delivered a perfect set...",
    "joke_invis_017_punch": "The crowd just stared at a floating microphone. Tough room. Toughest room.",
    "joke_invis_018_setup": "Why did the invisible man stop going to parties? He'd show up on time, bring a nice dish, mingle, try his best...",
    "joke_invis_018_punch": "And spend the whole night being asked to hold everyone's coats. He was a coat rack with feelings.",
    "joke_invis_019_setup": "What did the doctor tell the invisible man? \"I've run the tests, checked the charts, looked everywhere twice\"...",
    "joke_invis_019_punch": "\"Honestly, I can't find anything wrong with you.\" Best news he'd heard in a while.",
    "joke_invis_020_setup": "Why is the invisible man a great houseguest? Quiet, tidy, never in the way, you don't even know he's there...",
    "joke_invis_020_punch": "Which is also why you keep forgetting to feed him. He's not complaining. He's mostly not complaining.",
    "joke_invis_021_setup": "What did the invisible man do at the crowded concert? He walked right to the front, best spot in the house, nobody blocking...",
    "joke_invis_021_punch": "Finally a real perk. He'd been waiting his whole life for this one to pay off.",
    "joke_invis_022_setup": "Why did the invisible man love the color of his new car? The dealer talked up the finish, the shine, the paint job...",
    "joke_invis_022_punch": "He said \"just make it match me.\" They handed him keys to an empty parking spot.",
    "joke_invis_023_setup": "What happened when the invisible man joined the choir? Beautiful voice, hit every note, showed up to every practice...",
    "joke_invis_023_punch": "The director kept saying \"who is that?\" and never once looked down. Right there. Front row.",
    "joke_invis_024_setup": "Why did the invisible man get the quiet table at the restaurant? He asked for a nice spot, made the reservation, dressed up...",
    "joke_invis_024_punch": "They sat him in the back by the kitchen. \"Nobody'll bother you here.\" Story of his life.",
    "joke_invis_025_setup": "What did the invisible man say when someone finally noticed him? He froze. He teared up. His whole heart lifted...",
    "joke_invis_025_punch": "\"You can... you can see me?\" She said, \"No, I heard your stomach growl.\" Close enough. He'd take it.",
    "joke_invis_026_setup": "Why did the invisible man become a night watchman? Perfect eyesight, never sleeps on the job, blends right in...",
    "joke_invis_026_punch": "The only downside — even the burglars walked right past him. Rude, honestly.",
    "joke_invis_027_setup": "What happened when the invisible man went trick-or-treating? He didn't need a costume, saved money, walked right up to the door...",
    "joke_invis_027_punch": "\"Where's your costume, kid?\" He said, \"I'm an invisible man.\" \"Sure you are.\" Doors don't open easy for him.",
    "joke_invis_028_setup": "Why did the invisible man love the buffet? Nobody watching, nobody judging, second and third plates, no shame...",
    "joke_invis_028_punch": "Finally, being unseen paid off. Small victories. He counts them all.",
    "joke_invis_029_setup": "What did the invisible man's teacher write on his report card? She thought hard, tapped her pen, tried to remember a single thing...",
    "joke_invis_029_punch": "\"Present.\" That's it. That's the whole review. He framed it anyway.",
    "joke_invis_030_setup": "Why did the invisible man never win an argument? He had the facts, the logic, the perfect comeback ready...",
    "joke_invis_030_punch": "And everyone just kept talking over the empty chair. He knows he's right. That has to be enough.",
    "joke_invis_031_setup": "What happened when the invisible man tried online dating? Great conversation, real connection, she was excited to meet...",
    "joke_invis_031_punch": "He showed up early, waved, called her name. She left saying he stood her up. He did not.",
    "joke_invis_032_setup": "Why did the invisible man make a great therapist? He listens, he never interrupts, he holds all your secrets safe...",
    "joke_invis_032_punch": "You just occasionally forget you're paying an empty couch. Best listener in town, though.",
    "joke_invis_033_setup": "What did the invisible man say at the family portrait? \"Everybody scoot in, make room, I'll stand right in the middle\"...",
    "joke_invis_033_punch": "They framed it and hung it up. There's a mysterious gap by the fireplace to this day.",
    "joke_invis_034_setup": "Why did the invisible man love the elevator? Small space, close quarters, surely someone would notice him now...",
    "joke_invis_034_punch": "Nope. Fourteen floors of people staring at their phones. He felt right at home.",
    "joke_invis_035_setup": "What happened when the invisible man went to the DMV? He took a number, waited three hours, filled out every form...",
    "joke_invis_035_punch": "\"Now serving... an empty chair?\" He'd finally blended in perfectly. First time it ever helped.",
    "joke_invis_036_setup": "Why did the invisible man make the best babysitter? The kids can't see him, so they behave, thinking nobody's watching...",
    "joke_invis_036_punch": "Little do they know. He sees everything. He is the reason the cookies stay in the jar.",
    "joke_invis_037_setup": "What did the invisible man say at his own retirement party? Forty years of service, a nice cake, a speech all prepared...",
    "joke_invis_037_punch": "They gave the gold watch to the guy standing next to his empty chair. He clapped for him anyway.",
    "joke_invis_038_setup": "Why did the invisible man love a snowy day? Footprints appearing out of nowhere, a scarf floating down the street...",
    "joke_invis_038_punch": "For once, people could tell where he was. He never wanted the snow to melt.",
    "joke_invis_039_setup": "What happened when the invisible man tried to return something? He had the receipt, the box, a totally valid reason...",
    "joke_invis_039_punch": "\"Next in line!\" He was the line. He'd been the whole line for an hour.",
    "joke_invis_040_setup": "Why did the invisible man make a great magician's assistant? \"And now I'll make my assistant disappear!\" Big flourish, the reveal...",
    "joke_invis_040_punch": "Nothing happened, because he was already gone. Best trick in the show, technically.",
    "joke_invis_041_setup": "What did the invisible man love about the rain? The drops landing on his shoulders, outlining him, making him real for a second...",
    "joke_invis_041_punch": "He'd stand out there for hours. Everyone thought he was odd. He was just... visible.",
    "joke_invis_042_setup": "Why did the invisible man stop complaining to customer service? \"Please hold, your call is important to us,\" on repeat, for an hour...",
    "joke_invis_042_punch": "He realized — for once — they treat everyone exactly like they treat him. Weirdly comforting.",
    "joke_invis_043_setup": "What happened when the invisible man went to the fancy restaurant? He dressed up, ordered the good wine — the grape juice, keep it clean —",
    "joke_invis_043_punch": "and the waiter poured a glass for the empty seat all night. Best service he'd ever gotten.",
    "joke_invis_044_setup": "Why did the invisible man love the fog? Everyone else stumbling around, bumping into things, lost and squinting...",
    "joke_invis_044_punch": "For one beautiful morning, everybody knew exactly how he feels every single day.",
    "joke_invis_045_setup": "What did the invisible man do when he won the lottery? Right numbers, real ticket, marched up to claim it, so excited...",
    "joke_invis_045_punch": "\"Sir, there's no one here.\" He's rich. Technically. He just can't prove he exists to collect it.",
    "joke_invis_046_setup": "Why did the invisible man make a great goalie? The other team can't see him, can't aim, can't figure out the angles...",
    "joke_invis_046_punch": "Undefeated. Also never once got carried off the field on anyone's shoulders. Trade-offs.",
    "joke_invis_047_setup": "What happened when the invisible man went to the comedy club? He laughed the loudest, clapped the hardest, had the best time...",
    "joke_invis_047_punch": "The comedian said, \"Somebody's really enjoying this — where are you?\" Front and center, as always.",
    "joke_invis_048_setup": "Why did the invisible man love his cat? The cat can't see him either, but it sits right on his lap anyway, purring...",
    "joke_invis_048_punch": "Somehow the cat always knows where he is. First one who ever did. He'd die for that cat.",
    "joke_invis_049_setup": "What did the invisible man say when someone sat on him? Full weight, right down on the bench, no idea, getting comfortable...",
    "joke_invis_049_punch": "\"Excuse me — occupied.\" She screamed. He apologized. Honestly, nice to make an impression.",
    "joke_invis_050_setup": "What's the best thing about being the invisible man? Sure, nobody sees you, nobody picks you, nobody saves you a seat...",
    "joke_invis_050_punch": "But the ones who bother to look — really look — those are the good ones. You've got a couple. That's plenty.",
    "joke_squirrel_001_setup": "What does getting one thing done actually look like? You walk in for your keys, you see a cup, you take the cup to the kitchen, you notice the dishes, the phone rings...",
    "joke_squirrel_001_punch": "Three hours later you find your keys and you STILL haven't left. Sound familiar? Yeah. Thought so.",
    "joke_squirrel_002_setup": "How many tabs does the average person have open right now? Not on the computer — in their head. The list, the thing, the other thing, wait what was I...",
    "joke_squirrel_002_punch": "Forty-seven. The answer is forty-seven. And one of them's playing music you can't find.",
    "joke_squirrel_003_setup": "What's the fastest way to forget why you walked into a room? Walk into the room. That's it. That's the whole trick. You had it, it was right there...",
    "joke_squirrel_003_punch": "And now you're just standing in the kitchen like you're waiting for it to introduce itself.",
    "joke_squirrel_004_setup": "You ever start ten things and finish zero? Laundry's in the washer since Tuesday, half-painted wall, six browser tabs, a snack you forgot you made...",
    "joke_squirrel_004_punch": "But hey — you started strong on all of them. That's practically a personality type. It's mine, actually.",
    "joke_squirrel_005_setup": "What were we even talking about? You were making a point, a good one, you were ON it, everybody was listening...",
    "joke_squirrel_005_punch": "Then a bird went by the window and it was just... gone. Anyway. What were we saying?",
    "joke_squirrel_006_setup": "How do you know you've got a busy brain? You lie down to sleep and suddenly it's time to replay every decision since 2004 and one embarrassing thing from middle school...",
    "joke_squirrel_006_punch": "Your brain's got big plans for you at 2 a.m. None of them are sleep.",
    "joke_squirrel_007_setup": "What's a to-do list actually for? It's not to get things done — it's to write down the thing, feel accomplished, lose the list...",
    "joke_squirrel_007_punch": "Then find it in three weeks and go \"huh, never did any of this.\" A little keepsake of your intentions.",
    "joke_squirrel_008_setup": "Why'd you open the fridge? You don't know. You're not hungry. You were doing something else entirely a second ago...",
    "joke_squirrel_008_punch": "But the fridge knows. The fridge always knows. Just gonna stand in the cold light and think about it.",
    "joke_squirrel_009_setup": "What happens when you finally sit down to relax? You get comfortable, exhale, and BING — your brain remembers eleven things you forgot...",
    "joke_squirrel_009_punch": "Relaxing is just the quiet before your own to-do list ambushes you.",
    "joke_squirrel_010_setup": "Why did you walk into the garage? You marched out there with purpose, real intention, a mission in your heart...",
    "joke_squirrel_010_punch": "And now you're just holding a screwdriver, unsure who you are or how you got here.",
    "joke_squirrel_011_setup": "How does one small errand become a whole day? You go to return one thing, then you're at three stores, you got gas, you called your sister...",
    "joke_squirrel_011_punch": "And you never returned the thing. It's still in the car. It'll be there next week too.",
    "joke_squirrel_012_setup": "What's the most dangerous phrase in your own head? \"I'll just do this one quick thing first.\" Famous last words. The gateway to chaos...",
    "joke_squirrel_012_punch": "Four unrelated tasks later, you've forgotten the original quick thing entirely.",
    "joke_squirrel_013_setup": "Why is your phone always at two percent? You had all day to charge it, you saw the warning, you meant to, you really did...",
    "joke_squirrel_013_punch": "But something shiny happened between \"I should charge this\" and every single time.",
    "joke_squirrel_014_setup": "What do you call it when you put something in a \"safe place\"? You were being so responsible, so organized, so proud of your foresight...",
    "joke_squirrel_014_punch": "Gone. Forever. The safest place is the one place you'll never look again.",
    "joke_squirrel_015_setup": "How do you cook one meal? You start the pasta, then you unload the dishwasher, then you check your phone, then you smell smoke...",
    "joke_squirrel_015_punch": "Cooking is just a series of small fires you barely stay ahead of. Dinner's ready-ish!",
    "joke_squirrel_016_setup": "Why did you come upstairs? You climbed all fourteen steps with total conviction, a clear goal, a strong start...",
    "joke_squirrel_016_punch": "And it left you at step twelve. So now you're just... up here. Living up here now, apparently.",
    "joke_squirrel_017_setup": "What happens when someone asks \"what did you do today?\" You were busy — you know you were busy, you didn't stop for one second...",
    "joke_squirrel_017_punch": "And you cannot name a single thing. The busiest nothing anyone ever accomplished.",
    "joke_squirrel_018_setup": "Why do you have seventeen half-finished water bottles around the house? You started one in the kitchen, forgot it, started one upstairs, forgot that...",
    "joke_squirrel_018_punch": "Archaeologists will study these someday and understand exactly how your brain works.",
    "joke_squirrel_019_setup": "What's it like grocery shopping without a list? You go in for milk, you leave with candles, a plant, three snacks, and a throw pillow...",
    "joke_squirrel_019_punch": "No milk. Never the milk. The milk was the one thing and it never had a chance.",
    "joke_squirrel_020_setup": "Why did you open a new tab? You had a question, a real one, an important one, you needed the answer right now...",
    "joke_squirrel_020_punch": "Six tabs deep and you're watching a video about how glass is made. The original question is gone.",
    "joke_squirrel_021_setup": "What happens when you try to clean one drawer? \"This'll take five minutes,\" you said. You found old photos. You found a mystery cord...",
    "joke_squirrel_021_punch": "Now every drawer in the house is open and you're sitting on the floor reading a birthday card from 2011.",
    "joke_squirrel_022_setup": "Why is doing the dishes a two-hour event? You start rinsing, then you reorganize a cabinet, then you find expired spices, then you research spices...",
    "joke_squirrel_022_punch": "The dishes are still in the sink. But you learned a lot about cumin.",
    "joke_squirrel_023_setup": "What's your brain doing during an important conversation? You're nodding, you're listening, you're right there... mostly... and then —",
    "joke_squirrel_023_punch": "\"Did I lock the front door?\" Gone. You'll catch the last half. Probably.",
    "joke_squirrel_024_setup": "Why did you take a picture of where you parked? Smart. Responsible. Prepared. You even said the row number out loud to yourself...",
    "joke_squirrel_024_punch": "Then you deleted it by accident looking for it later. Full circle. You're back to wandering.",
    "joke_squirrel_025_setup": "How does laundry actually work in your house? You wash it, you dry it, you're on a roll, you're a machine, you're unstoppable...",
    "joke_squirrel_025_punch": "It lives in the basket now. It'll live in the basket for eight days. The basket is where clothes retire.",
    "joke_squirrel_026_setup": "Why did you set seven alarms? Each one a promise, a plan, a fresh start, a new chance to be a morning person...",
    "joke_squirrel_026_punch": "You'll turn off all seven in your sleep and remember none of it. Your sleeping self is very efficient.",
    "joke_squirrel_027_setup": "What happens when you finally have a free afternoon? Big plans. So many plans. You were going to be productive, you had a whole vision...",
    "joke_squirrel_027_punch": "You spent it looking at your phone and reorganizing the vision. Tomorrow. Tomorrow for sure.",
    "joke_squirrel_028_setup": "Why do you have forty-three unread reminders? Each one felt urgent when you set it, essential, a thing you'd definitely handle...",
    "joke_squirrel_028_punch": "Now they're just a little wall of things past-you was very worried about. Past-you needs to relax.",
    "joke_squirrel_029_setup": "What's it like trying to leave the house? Keys, phone, wallet — okay, going — wait, is the stove off? Back inside. Now where's my phone...",
    "joke_squirrel_029_punch": "Leaving the house is a four-part quest and you are the least reliable member of the party.",
    "joke_squirrel_030_setup": "Why did you start three books at once? This one for the couch, this one for bed, this one for \"I don't know, a mood\"...",
    "joke_squirrel_030_punch": "You're forty pages into each and could not tell you a single character's name. But you're reading! Technically!",
    "joke_squirrel_031_setup": "What happens the moment your head hits the pillow? Total silence. Perfect calm. And then your brain goes \"hey, remember that thing? let's think about it\"...",
    "joke_squirrel_031_punch": "Your brain saved up all its best ideas for the exact worst time to have them.",
    "joke_squirrel_032_setup": "Why is your desk like that? There's a system. You swear there's a system. The piles mean something...",
    "joke_squirrel_032_punch": "Only you can navigate it, and even you're not sure anymore. It's less a desk, more an archaeological dig.",
    "joke_squirrel_033_setup": "What's it like paying bills? You sit down, ready, focused, this is happening — and then you see one interesting envelope...",
    "joke_squirrel_033_punch": "An hour later you've researched a vacation you can't afford and paid zero bills. Productive-adjacent.",
    "joke_squirrel_034_setup": "Why did you walk to the mailbox and come back with nothing? You went for the mail, but you saw a weed, then you waved at a neighbor, then a dog...",
    "joke_squirrel_034_punch": "You're back inside, empty-handed, and the mail is still out there. Living its own life.",
    "joke_squirrel_035_setup": "What happens when you try to watch one show? You pick something, then you check your phone, then you look up \"wait what else is that actor in\"...",
    "joke_squirrel_035_punch": "Ninety minutes later you've watched none of the show and read three full biographies. Great night, though.",
    "joke_squirrel_036_setup": "Why do you have a notes app full of chaos? Half a grocery list, a business idea, someone's name, \"buy the thing,\" a poem, a phone number...",
    "joke_squirrel_036_punch": "It's a window directly into your brain, and honestly? No notes. Well. Forty-seven notes.",
    "joke_squirrel_037_setup": "What's it like starting your morning routine? You had a plan — coffee, stretch, a nice calm start to the day, very intentional...",
    "joke_squirrel_037_punch": "You're now vacuuming a closet at 7 a.m. with cold coffee. The day got away early today.",
    "joke_squirrel_038_setup": "Why did you reread that same sentence four times? Your eyes are on the page, the words are right there, you're \"reading\"...",
    "joke_squirrel_038_punch": "But your brain left the building three paragraphs ago. Welcome back. Start over.",
    "joke_squirrel_039_setup": "What happens when you decide to be organized? You buy the bins, the labels, the system, you watch the videos, you're inspired...",
    "joke_squirrel_039_punch": "The bins are now full of the stuff you were going to organize. Progress! Sort of! It's in ONE spot now!",
    "joke_squirrel_040_setup": "Why do you keep the receipt from 2019? You might need it, you think. For something. At some point. You can't say what...",
    "joke_squirrel_040_punch": "It's in a drawer with sixty of its friends. A little museum of \"just in case.\"",
    "joke_squirrel_041_setup": "What's it like trying to reply to a text? You read it, you think \"I'll answer that in a sec,\" you set the phone down...",
    "joke_squirrel_041_punch": "Three days later: \"so sorry, just seeing this!\" You were not just seeing it. You've seen it forty times.",
    "joke_squirrel_042_setup": "Why did you start cleaning the whole house at 10 p.m.? You couldn't sleep, you got an idea, the energy struck, and it must be obeyed...",
    "joke_squirrel_042_punch": "Now it's midnight, the closet's rearranged, and you have to be up at six. Worth it. Probably. No.",
    "joke_squirrel_043_setup": "What happens when you finally find the thing you lost? You searched for an hour, tore the place apart, gave up, moved on...",
    "joke_squirrel_043_punch": "It was in your hand the whole time. Or your pocket. Or on your head. It's always on your head.",
    "joke_squirrel_044_setup": "Why do you have twelve browser bookmarks called \"read later\"? Fascinating articles, important stuff, things you genuinely meant to get to...",
    "joke_squirrel_044_punch": "\"Later\" is a magical land where nothing is ever actually read. Beautiful place. Never been.",
    "joke_squirrel_045_setup": "What's it like meal prepping? You buy all the containers, all the veggies, you're going to be so healthy and organized...",
    "joke_squirrel_045_punch": "The veggies become a science experiment in the crisper drawer. You ordered takeout. Again. It's fine.",
    "joke_squirrel_046_setup": "Why did you say \"I'll remember, I don't need to write it down\"? You were so sure. So confident. Your memory, this one time, would come through...",
    "joke_squirrel_046_punch": "It did not. It never does. Write it down. Write everything down. Trust nothing.",
    "joke_squirrel_047_setup": "What happens when you get a great idea in the shower? It's brilliant, it's perfect, it's the best idea you've ever had, you'll definitely remember it...",
    "joke_squirrel_047_punch": "By the time you're dry, it's gone forever. The shower keeps all your best ideas. Greedy.",
    "joke_squirrel_048_setup": "Why is there a sock on the stairs? You were carrying it up, but then you saw something, and set it down \"for a second\"...",
    "joke_squirrel_048_punch": "That sock lives there now. It's part of the house. Everyone just steps over it. It's family.",
    "joke_squirrel_049_setup": "What's it like when someone gives you three instructions at once? You catch the first one clearly, you're locked in, then two and three arrive together...",
    "joke_squirrel_049_punch": "And your brain files all three under \"I'll figure it out.\" You will not. You caught one. Good luck.",
    "joke_squirrel_050_setup": "So what's the secret to getting everything done? There isn't one. You bounce, you scatter, you forget, you circle back, you somehow make it work...",
    "joke_squirrel_050_punch": "And that busy, jumpy, hundred-things-at-once brain of yours? It's not a flaw. It's just a lot of life happening at once. You're doing great.",
}

def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    if "PASTE_YOUR" in EL_KEY or "PASTE_YOUR" in VOICE_ID:
        print("WARNING: set EL_KEY and VOICE_ID first (edit file or set env vars)."); return
    url = f"https://api.elevenlabs.io/v1/text-to-speech/{VOICE_ID}"
    headers = {"xi-api-key": EL_KEY, "Content-Type": "application/json"}
    total = len(LINES); done = 0
    for fname, text in LINES.items():
        out = os.path.join(OUT_DIR, fname + ".mp3")
        if os.path.exists(out):
            print(f"skip (exists): {fname}"); done += 1; continue
        payload = {"text": text, "model_id": MODEL,
                   "voice_settings": {"stability":0.5,"similarity_boost":0.75,"style":0.0,"speed":SPEED}}
        try:
            r = requests.post(url, headers=headers, json=payload, timeout=60)
            if r.status_code == 200:
                with open(out,"wb") as f: f.write(r.content)
                done += 1; print(f"[{done}/{total}] saved {fname}.mp3")
            else:
                print(f"ERROR {fname}: {r.status_code} {r.text[:120]}")
        except Exception as e:
            print(f"ERROR {fname}: {e}")
        time.sleep(0.4)
    print(f"\nDone. {done}/{total} clips in {OUT_DIR}/ at speed {SPEED}.")
if __name__ == "__main__":
    main()